#!/usr/bin/env bash

for i in `ls ..`
  do
    if [ ! -e $HOME/../$i ]
      then
        ln -s `pwd`/../$i $HOME/.$i
      fi
  done

mkdir $HOME/.config || true
ln -s `pwd`/../.nvim $HOME/.config/nvim
